# //////   PORTABLE SHOP CONFIG    \\\\\\
#
#
#
#
#
#
#
About: 'A portable shop by H3rzius'
#
#
#
url: 'jdbc:mysql://localhost/pshop'
username: 'root'
password: ''
commandNotExistException: 'ERROR: This command doesnt exist!'
alreadycreated: 'You have already created a shop!'